apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gider-app
  namespace: home
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - gider.railguncnr.com
      secretName: wildcard-tls
  rules:
    - host: gider.railguncnr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gider-app
                port:
                  number: 80
