apiVersion: v1
kind: Secret
metadata:
  name: gider-app-secret
  namespace: home
type: Opaque
stringData:
  DB_HOST: "postgresql.devops.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "postgre"
  DB_PASSWORD: "vW82*RA%F5V#"
  DB_NAME: "home-expense"
  JWT_SECRET: "0FcHTsjXRnx8ooQJaqqOUq+zGXX/tHApuGBC52sK+a0="
