apiVersion: v1
kind: Secret
metadata:
  name: gider-app-secret
  namespace: home
type: Opaque
stringData:
  DB_HOST: "postgresql.home.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "gider"
  DB_PASSWORD: "CHANGEME"
  DB_NAME: "gider_db"
  JWT_SECRET: "CHANGEME"
